### ISSUE TITLE
Add support for CRD operation for StorageClasses.

### ISSUE THREAD

**Issue by princerachit** [openebs/CITF#34]
Currently CITF does not support CRD operation for Storage classes. This support needs to be added. The code should also support reading/parsing SC definition from a yaml file .

Please refer to [this file](https://github.com/openebs/CITF/blob/master/utils/k8s/k8s.go) to see existing supported code.

**Please comment if you want to be assigned for this issue.**

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[hacktoberfest2018](https://openebs-community.slack.com/messages/hacktoberfest2018/) channel on slack. Ping us here if you want to discuss anything around hacktoberfest

**Comment by sayanchowdhury** [comment]
Hi, I would like to take up this issue.

**Comment by Akash4927** [comment]
@sayanchowdhury Please go ahead.

**Comment by mukeshmk** [comment]
@Akash4927 I am starting to work on this.
