### ISSUE TITLE
Add support for Read operation for PersistentVolume.

### ISSUE THREAD

**Issue by princerachit** [openebs/CITF#35]
Currently CITF does not support READ operation for Persistent Volume. This support needs to be added. The code should also support reading/parsing Persistent Volume from a yaml file.

Please refer to [this file](https://github.com/openebs/CITF/blob/master/utils/k8s/k8s.go) to see existing supported code.

**Please comment if you want to be assigned for this issue.**

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[hacktoberfest2018](https://openebs-community.slack.com/messages/hacktoberfest2018/) channel on slack. Ping us here if you want to discuss anything around hacktoberfest

**Comment by AdityaMisra** [comment]
Hey, I would like to work on this issue.

**Comment by AdityaMisra** [comment]
@sonasingh46 sorry about not keeping you guys updated. I'll take some more time. If you want you can assign this issue to someone else.

**Comment by mukeshmk** [comment]
@sonasingh46 can I work on this Issue? hope it's okay with you @AdityaMisra .

**Comment by sonasingh46** [comment]
@AdityaMisra 
No worries. You can take some other issues that will be opened soon as we need this one to move forward.
Thanks Aditya and feel free to post questions,queries etc.

**Comment by sonasingh46** [comment]
@mukeshmk 
Thanks!
PR is already there. We will go by that.
Please look out for the issues that will be opened soon.

**Comment by sonasingh46** [comment]
@Akash4927 
Can we go ahead and review the PR and link to this issue.
