### ISSUE TITLE
Add support for CRD operation for PersistentVolumeClaim.

### ISSUE THREAD

**Issue by princerachit** [openebs/CITF#36]
Currently CITF does not support CRD operation for Persistent Volume Claim. This support needs to be added. The code should also support reading/parsing Persistent Volume Claim from a yaml file.

Please refer to [this file](https://github.com/openebs/CITF/blob/master/utils/k8s/k8s.go) to see existing supported code.

**Please comment if you want to be assigned for this issue.**

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[hacktoberfest2018](https://openebs-community.slack.com/messages/hacktoberfest2018/) channel on slack. Ping us here if you want to discuss anything around hacktoberfest

**Comment by farhaanbukhsh** [comment]
Hey I would like to take this up :)

**Comment by Akash4927** [comment]
@farhaanbukhsh Please go ahead

**Comment by farhaanbukhsh** [comment]
Hey @Akash4927 can you help me to get started? I am not able to understand where to start?
