### ISSUE TITLE
Add support for CRD operation for Deployment

### ISSUE THREAD

**Issue by princerachit** [openebs/CITF#37]
Currently CITF does not support CRD operation for Deployment. This support needs to be added. The code should also support reading/parsing Deployment from a yaml file .

Please refer to [this file](https://github.com/openebs/CITF/blob/master/utils/k8s/k8s.go) to see existing supported code.

**Please comment if you want to be assigned for this issue.**

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[hacktoberfest2018](https://openebs-community.slack.com/messages/hacktoberfest2018/) channel on slack. Ping us here if you want to discuss anything around hacktoberfest

**Comment by mukeshmk** [comment]
I would like to work on this Issue.

**Comment by Akash4927** [comment]
@mukeshmk Please go ahead
