### ISSUE TITLE
Add support for Read operation for custom resources

### ISSUE THREAD

**Issue by princerachit** [openebs/CITF#38]
Currently CITF does not support Read operation for custom resources. This support needs to be added.

The client should be able to pass `customresourcedefinition` name and `customresource` and should get yaml/json of the resource.

Please refer to [this file](https://github.com/openebs/CITF/blob/master/utils/k8s/k8s.go) to see existing supported code.

**Please comment if you want to be assigned for this issue.**

Help links:
[Contributors guide](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
[hacktoberfest2018](https://openebs-community.slack.com/messages/hacktoberfest2018/) channel on slack. Ping us here if you want to discuss anything around hacktoberfest

**Comment by krishnakarthik1309** [comment]
@princerachit I would like to work on it. To be clear the input parameters will be `crdName`, `customresource`, `namespace` and output should be to in `yaml` format.

**Comment by krishnakarthik1309** [comment]
I have a doubt. Should the logic be based on executing `kubectl` command or through `client-go`. If it is through `client-go` I think we need `Custom resource struct` to unmarshal/deserialize.

**Comment by sonasingh46** [comment]
@krishnakarthik1309 
We define the structs in a separate package. And yes you will get to know the structs for the CR that is already there in other projects. You will need to utilise that.

**Comment by sonasingh46** [comment]
@krishnakarthik1309 
You will require to use openebs client here which will do the job.
cc @Akash4927

**Comment by Akash4927** [comment]
HI @krishnakarthik1309 Instead of a struct, I think we can use the clientset of the CRDs that are already present in `openebs/maya` and `openebs/node-disk-manager` repo.

**Comment by sonasingh46** [comment]
This has been addressed.
See following:
https://github.com/openebs/CITF/issues/45
https://github.com/openebs/CITF/issues/56
https://github.com/openebs/CITF/issues/48
https://github.com/openebs/CITF/issues/47
https://github.com/openebs/CITF/issues/46
