### ISSUE TITLE
Add support for Disk CR

### ISSUE THREAD

**Issue by Akash4927** [openebs/CITF#48]
Add support to list, get and delete the Disk CR which is a clustered-scope resource.

you have to use the package `openebsv1aplha1 "github.com/openebs/CITF/pkg/apis/openebs.io/v1alpha1"`

**Comment by MuthukumarHelios** [comment]
I would like to work on this issue

**Comment by MuthukumarHelios** [comment]
[see pull](https://github.com/openebs/CITF/pull/50l) if the changes will solve the issue Please close this issue

**Comment by kmjayadeep** [comment]
If the pr mentions this issue, merging the pr will automatically close the issue
