### ISSUE TITLE
Is it possible to return address of local scope variable?

### ISSUE THREAD

**Issue by bharathpgp** [openebs/CITF#60]
https://github.com/openebs/CITF/blob/80c588255c1a37d0e953b6f530a3ceaa38aff5ac/citf_options/citf_options.go#L13-L21
@a4abhishek scope of the local variable(citfCreateOptions) ends within this function itself.

**Comment by MuthukumarHelios** [comment]
you can return the local Scope which having the global export ting type 

``go
 func CreateOptionsIncludeAll(configPath string) *CreateOptions { 
 	var citfCreateOptions CreateOptions 
 	citfCreateOptions.ConfigPath = configPath 
citfCreateOptions.EnvironmentInclude = true 
}

configPath := CreateOptionsIncludeAll("configPath").ConfigPath  
fmt.Println(configPath) ==> you can access the values

**Comment by bharathpgp** [comment]
@MuthukumarHelios can you refer some online resource to know more about it.
